"""create models user and history

Revision ID: 067b2955b728
Revises: 
Create Date: 2026-04-05 14:11:14.165954

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067b2955b728'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token_hash', sa.String(length=64), nullable=True),
    sa.Column('email_verification_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_users_created_at'), 'auth_users', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_index(op.f('ix_auth_users_email_verification_token_hash'), 'auth_users', ['email_verification_token_hash'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('access_token', sa.String(length=128), nullable=False),
    sa.Column('refresh_token', sa.String(length=128), nullable=False),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_access_expires_at'), 'auth_sessions', ['access_expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_access_token'), 'auth_sessions', ['access_token'], unique=True)
    op.create_index(op.f('ix_auth_sessions_created_at'), 'auth_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_refresh_expires_at'), 'auth_sessions', ['refresh_expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_refresh_token'), 'auth_sessions', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_refresh_token'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_refresh_expires_at'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_created_at'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_access_token'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_access_expires_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_auth_users_email_verification_token_hash'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_created_at'), table_name='auth_users')
    op.drop_table('auth_users')
    # ### end Alembic commands ###
